source 'https://github.com/cocoapods/specs.git'

#plugin 'cocoapods-bin'

use_frameworks!

platform :ios, '12.0'

target 'TestSwiftOC_Example' do
  pod 'TestSwiftOC', :path => '../'

  target 'TestSwiftOC_Tests' do
    inherit! :search_paths

    
  end
end
